### ISSUE TITLE
arguments as promises

### ISSUE THREAD

**Issue by calvinmetcalf** [matthew-andrews/denodeify#14]
some things that came up when talking to the rsvp people about how their version worked led to me perfing quite a few edge cases before I settled on [this code](https://github.com/calvinmetcalf/lie-denodify/blob/master/lib/denodify.js) for my version of denodify.  Feel free to repurpose as much or as little of the code as you'd like the main issues it solves involving denodeified functions being able to accept arguments as promises.

**Comment by matthew-andrews** [comment]
i've not yet needed this, although would happily accept pull requests for this going to provisionally close this.
