### ISSUE TITLE
test with mkdirp

### ISSUE THREAD

**Issue by triblondon** [matthew-andrews/denodeify#21]
npm module

**Comment by matthew-andrews** [comment]
>  Andrew:  figured out the mkdirp thing.  when I bind it, I make a function that gets called with one arg, the dir to create.  But then() invokes it with an extra one - the fulfilment value from the previous promise.  denodeify then invokes the underlying node function with both of those args and adds the callback function as a third arg.  mkdirp accepts 2-4 args, so if you give it three, it thinks the second is an options object.

Thanks, @triblondon !
