### ISSUE TITLE
Document using denodeify against a method

### ISSUE THREAD

**Issue by BrianRossmajer** [matthew-andrews/denodeify#23]
It would be great if the documentation would mention how to denodeify methods as well as functions; perhaps something like this (borrowing from the Q library documentation):

Note that if you have a method that uses the Node.js callback pattern, as opposed to just a function, you will need to bind its this value before passing it to denodeify, like so:

var Kitty = mongoose.model("Kitty");
var brokenFind = denodeify( Kitty.find );  // the find method won't have the right 'this' defined
var findKitties = denodeify( Kitty.find.bind(Kitty) );

**Comment by matthew-andrews** [comment]
Great idea :+1:.  It could go as a second example before the line `More complex example…`.

Is this something you would be happy to prepare a pull request for or would you prefer if I typed something up?

**Comment by BrianRossmajer** [comment]
If the text above works as-is, I'll be happy to do a pull request -- but if you'll want to change it anyway, it probably makes sense for you to write it up... the latter would be my preference I suppose :-)

Thanks!

**Comment by marvinroger** [comment]
I just got stuck for an hour about that. @BrianRossmajer, the text you wrote is perfectly clear, I think it is fine. Could you submit a PR if @matthew-andrews is ok?

**Comment by matthew-andrews** [comment]
my bad I completely missed @BrianRossmajer's comment.  I've done this:

https://github.com/matthew-andrews/denodeify/pull/24

**Comment by BrianRossmajer** [comment]
Looks great to me, thanks!
